FROM ghcr.io/agile-learning-institute/stage0_mongodb_api:latest

# Default environment configuration values
# ENV MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
# ENV INPUT_FOLDER=/input
# ENV AUTO_PROCESS=false
# ENV EXIT_AFTER_PROCESSING=false
# ENV LOAD_TEST_DATA=false
# ENV MONGODB_API_PORT=8081
ENV MONGO_DB_NAME=floppy

# Copy files 
COPY input /input